# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rohankumar770123 #database
      MONGO_INITDB_ROOT_PASSWORD: Ny9paGszOi7cF5Vo
      MONGO_INITDB_ROOT_DB: mydb
    ports:
    - '27017:27017'